services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      TYPE: FORGE
      CF_API_KEY: $2a$10$NN/M1Nj3OCK5vzHjnWL4sezaKqhaqRIQEBe5EHPBEnwC3rixS7zTK
      VERSION: 1.20.1
      CURSEFORGE_FILES: |
        geckolib
        aquaculture
        naturalist
    ports:
      - "53687:25565"
