services:
  mc:
    image: itzg/minecraft-server
    volumes:
    - ./modpacks:/modpacks:ro
    - data:/data
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/SIMPLE-SERVER-FILES-0.3.20.zip
    ports:
      - "25865:25565"

volumes:
  data: {}
