services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: FORGE
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "true"
    ports:
      - "25865:25565"
    volumes:
      - data:/data
      - ./mods.txt:/extras/mods.txt:ro

volumes:
  data:
